<?php
$hookvalue = array(
    array(
        'name' => 'displaySmartBlogLeft',
        'title' => 'displaySmartBlogLeft',
        'description' => 'This is blog page left column',
        'position' => 1,
        'live_edit' => 0,
    ),
    array(
        'name' => 'displaySmartBlogRight',
        'title' => 'displaySmartBlogRight',
        'description' => 'This is blog page Right column',
        'position' => 1,
        'live_edit' => 0,
    ),
    array(
        'name' => 'displaySmartBeforePost',
        'title' => 'displaySmartBeforePost',
        'description' => 'This is blog Single page before blog post',
        'position' => 1,
        'live_edit' => 0,
    ),
    array(
        'name' => 'displaySmartAfterPost',
        'title' => 'displaySmartAfterPost',
        'description' => 'This is blog Single page after blog post',
        'position' => 1,
        'live_edit' => 0,
    ),
    array(
        'name' => 'actionsbnewpost',
        'title' => 'actionsbnewpost',
        'description' => 'this is action hook.',
        'position' => 1,
        'live_edit' => 0,
    ),
    array(
        'name' => 'actionsbupdatepost',
        'title' => 'actionsbupdatepost',
        'description' => 'this is action hook.',
        'position' => 1,
        'live_edit' => 0,
    ),
    array(
        'name' => 'actionsbdeletepost',
        'title' => 'actionsbdeletepost',
        'description' => 'this is action hook.',
        'position' => 1,
        'live_edit' => 0,
    ),
    array(
        'name' => 'actionsbtogglepost',
        'title' => 'actionsbtogglepost',
        'description' => 'this is action hook.',
        'position' => 1,
        'live_edit' => 0,
    ),
     array(
        'name' => 'actionsbnewcat',
        'title' => 'actionsbnewcat',
        'description' => 'this is action hook.',
        'position' => 1,
        'live_edit' => 0,
    ),
    array(
        'name' => 'actionsbupdatecat',
        'title' => 'actionsbupdatecat',
        'description' => 'this is action hook.',
        'position' => 1,
        'live_edit' => 0,
    ),
    array(
        'name' => 'actionsbdeletecat',
        'title' => 'actionsbdeletecat',
        'description' => 'this is action hook.',
        'position' => 1,
        'live_edit' => 0,
    ),
    array(
        'name' => 'actionsbtogglecat',
        'title' => 'actionsbtogglecat',
        'description' => 'this is action hook.',
        'position' => 1,
        'live_edit' => 0,
    ),
    array(
        'name' => 'actionsbpostcomment',
        'title' => 'actionsbpostcomment',
        'description' => 'this is action hook.',
        'position' => 1,
        'live_edit' => 0,
    ),
    array(
        'name' => 'actionsbappcomment',
        'title' => 'actionsbappcomment',
        'description' => 'this is action hook.',
        'position' => 1,
        'live_edit' => 0,
    ),
    array(
        'name' => 'actionsbsingle',
        'title' => 'actionsbsingle',
        'description' => 'this is action hook.',
        'position' => 1,
        'live_edit' => 0,
    ),
    array(
        'name' => 'actionsbcat',
        'title' => 'actionsbcat',
        'description' => 'this is action hook.',
        'position' => 1,
        'live_edit' => 0,
    ),
    array(
        'name' => 'actionsbsearch',
        'title' => 'actionsbsearch',
        'description' => 'this is action hook.',
        'position' => 1,
        'live_edit' => 0,
    ),
    array(
        'name' => 'actionsbheader',
        'title' => 'actionsbheader',
        'description' => 'this is action hook.',
        'position' => 1,
        'live_edit' => 0,
    ),
);
?>